package com.example.estate.model;

public enum DocumentType {
    PROPERTY_IMAGE,
    PROPERTY_VIDEO,
    PROPERTY_DOCUMENT,
    LEGAL_DOCUMENT,
    IDENTIFICATION_DOCUMENT,
    FINANCIAL_DOCUMENT,
    INSURANCE_DOCUMENT,
    SURVEY_DOCUMENT,
    TITLE_DEED,
    BUILDING_PLAN,
    OCCUPANCY_PERMIT,
    TAX_CLEARANCE,
    UTILITY_BILL,
    BANK_STATEMENT,
    INCOME_CERTIFICATE,
    REFERENCE_LETTER,
    CONTRACT_DOCUMENT,
    AGREEMENT_DOCUMENT,
    OTHER
}
