package com.example.estate.model;

public enum TemplateType {
    TENANCY_AGREEMENT,
    LEASE_AGREEMENT,
    SALE_CONTRACT,
    RENTAL_AGREEMENT,
    PROPERTY_MANAGEMENT_AGREEMENT,
    BROKERAGE_AGREEMENT,
    PROPERTY_INSPECTION_REPORT,
    PROPERTY_VALUATION_REPORT,
    LAND_TITLE_DOCUMENT,
    SURVEY_PLAN,
    BUILDING_PLAN,
    OCCUPANCY_PERMIT,
    PROPERTY_INSURANCE_POLICY,
    MORTGAGE_AGREEMENT,
    PROPERTY_TRANSFER_DEED
}
